openapi: 3.0.0
servers:
  - description: localhost #AWS Elastic Bean Stalk
    # url: http://vault-backend.eba-wrntzw3k.ap-south-1.elasticbeanstalk.com/api/v1
    url: http://localhost:3000/api/v1
info:
  version: 1.0.0
  title: DevCamper API
  description: Backend API for the DevCamper application to manage bootcamps, courses, reviews, users and authentication
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
consumes: application/json
produces: application/json
paths:
  /bootcamps:
    get:
      summary: Get all Bootcamps
      tags:
        - Bootcamps
      responses:
        '200':
          description: On success
        '400':
          description: On error
    post:
      summary: Create new Bootcamp
      tags:
        - Bootcamps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBootcampModel'
      responses:
        '200':
          description: On success
        '400':
          description: On error
  /bootcamps/{id}:
    get:
      parameters:
        - in: path
          name: id
          example: 5fdf43ebf6f3314e9ce3e4c0
          schema:
            type: string
          required: true
          description: Bootcamp ID
      summary: Get single Bootcamp
      tags:
        - Bootcamps
      responses:
        '200':
          description: On success
        '400':
          description: On error
    put:
      parameters:
        - in: path
          name: id
          example: 5fdf43ebf6f3314e9ce3e4c0
          schema:
            type: string
          required: true
          description: Bootcamp ID
      summary: Update Bootcamp
      tags:
        - Bootcamps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/UpdateBootcampModel'
      responses:
        '200':
          description: On success
        '400':
          description: On error
    delete:
      parameters:
        - in: path
          name: id
          example: 5fdf43ebf6f3314e9ce3e4c0
          schema:
            type: string
          required: true
          description: Bootcamp ID
      summary: Delete Bootcamp
      tags:
        - Bootcamps
      responses:
        '200':
          description: On success
        '400':
          description: On error
  /bootcamps/radius/{zipcode}/{distance}/{unit}:
    get:
      parameters:
        - in: path
          name: zipcode
          example: '02118' # Boston pincode
          schema:
            type: string
          required: true
          description: Zip Code
        - in: path
          name: distance
          example: 10
          schema:
            type: number
          required: true
          description: Distance
        - in: path
          name: unit
          example: mi
          schema:
            type: string
          required: true
          description: Distance Unit (mi/km)
      summary: Find Bootcamps within range
      tags:
        - Bootcamps
      responses:
        '200':
          description: On success
        '400':
          description: On error

#-------------------------------------------------------- Models for API's-------------------------------------------
#--------------------------------------------------------------------------------------------------------------------
#--------------------------------------------------------------------------------------------------------------------

components:
  schemas:
    CreateBootcampModel:
      required:
        - name
        - description
        - website
        - phone
        - email
        - address
        - careers
        - housing
        - jobAssistance
        - jobGuarantee
        - acceptGi
      properties:
        name:
          type: string
          example: 'Code Academy Bootcamp'
        description:
          type: string
          example: 'Code Academy is a full stack Java Bootcamp'
        website:
          type: string
          example: 'https://codeacademy.com'
        phone:
          type: string
          example: '(555) 555-5555'
        email:
          type: string
          example: 'enroll@codeacademy.com'
        address:
          type: string
          example: '233 Bay State Rd Boston MA 02215'
        careers:
          type: array
          items:
            type: string
          example: ['Web Development', 'Other', 'Business']
        housing:
          type: boolean
        jobAssistance:
          type: boolean
        jobGuarantee:
          type: boolean
        acceptGi:
          type: boolean
    UpdateBootcampModel:
      properties:
        name:
          type: string
          example: 'Code Academy Bootcamp'
        description:
          type: string
          example: 'Code Academy is a full stack Java Bootcamp'
        website:
          type: string
          example: 'https://codeacademy.com'
        phone:
          type: string
          example: '(555) 555-5555'
        email:
          type: string
          example: 'enroll@codeacademy.com'
        address:
          type: string
          example: '233 Bay State Rd Boston MA 02215'
        careers:
          type: array
          items:
            type: string
          example: ['Web Development', 'Other', 'Business']
        housing:
          type: boolean
        jobAssistance:
          type: boolean
        jobGuarantee:
          type: boolean
        acceptGi:
          type: boolean
